# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 20:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='DateTime')),
            ],
        ),
        migrations.CreateModel(
            name='MoodValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256, verbose_name='Description')),
                ('value', models.IntegerField(verbose_name='Mood_value')),
            ],
        ),
        migrations.AddField(
            model_name='mood',
            name='mood_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.MoodValues'),
        ),
        migrations.AddField(
            model_name='mood',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
